name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  check:
    name: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check --locked

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --locked -- -D warnings

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
